package:
  name: yaml
  version: "0.1.6"

source:
  fn: yaml-0.1.6.tar.gz
  url: http://pyyaml.org/download/libyaml/yaml-0.1.6.tar.gz

build:
  script: |
    ./configure --prefix=$PREFIX
    make
    make install

about:
  home: http://pyyaml.org/wiki/LibYAML
  license: MIT
