package:
  name: nose
  version: "1.3.4"

source:
  fn: nose-1.3.4.tar.gz
  url: https://pypi.python.org/packages/source/n/nose/nose-1.3.4.tar.gz
  md5: 6ed7169887580ddc9a8e16048d38274d

build:
  script: |
    python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - nose
  commands:
    - nosetests --version

about:
  home: http://readthedocs.org/docs/nose/
  license: LGPL2.1
