package:
  name: netcdf4  # Note, for consistency with anaconda, this is not netcdf4-python.
  version: 1.1.3

source:
  git_tag: v1.1.3rel
  git_url: https://github.com/Unidata/netcdf4-python.git

build:
  number: 1

requirements:
  build:
    - python
    - numpy 1.8.*
    - libnetcdf
  run:
    - python
    - numpy 1.8.*
    - libnetcdf

test:
  imports:
    - netCDF4

