package:
  name: matplotlib
  version: 1.4.2

source:
  git_url: https://github.com/matplotlib/matplotlib
  git_tag: v1.4.2

build:
  number: 3

requirements:
  build:
    - python
    - numpy x.x
    - python-dateutil
    - nose
    - pyparsing
    - pytz
    - distribute
    - libpng
    - mock
  run:
    - mock
    - python
    - numpy x.x
    - python-dateutil
    - pytz
    - libpng
    - pyparsing


test:
  imports:
    - matplotlib
    - matplotlib.pyplot

