{% set version= "18.4" %}

package:
  name: setuptools
  version: {{ version }}

source:
  url: https://bitbucket.org/pypa/setuptools/get/{{ version }}.tar.gz
  fn: setuptools-{{ version }}.tar.gz
  patches:
     - conda.patch

build:
  number: 1
  preserve_egg_dir: True

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - pkg_resources
    - pkg_resources._vendor
    - pkg_resources._vendor.packaging
    - setuptools
    - setuptools.command
  commands:
    - easy_install --version

about:
  home: https://bitbucket.org/pypa/setuptools
  license: Python Software Foundation License or Zope Public License
  summary: 'Easily download, build, install, upgrade, and uninstall Python packages'
