package:
   name: conda-build
   version: 1.18.2

source:
  git_url: https://github.com/conda/conda-build
  git_tag: 1.18.2

requirements:
   build:
     - python
   run:
     - python
     - patchelf
     - conda

build:
  number: 0

test:
   commands:
     - CONDA_NPY=19 conda build --help
   imports:
     - conda_build
