package:
   name: conda-build
   version: 1.13.0

source:
  git_url: https://github.com/conda/conda-build
  git_tag: 1.13.0

requirements:
   build:
     - python
   run:
     - python
     - patchelf
     - conda

build:
  number: 1

test:
   commands:
     - conda build --help
   imports:
     - conda_build
