package:
  name: pytz
  version: 2013b

source:
  fn: pytz-2013b.tar.bz2
  url: https://pypi.python.org/packages/source/p/pytz/pytz-2013b.tar.bz2
  md5: 34f47470eedd5cd1faf6c3da2741967b

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - pytz

about:
  home: http://pytz.sourceforge.net
  license: MIT License

