package:
  name: conda-env
  version: 2.4.2

source:
  git_url: https://github.com/conda/conda-env
  git_tag: v2.4.2

build:
  always_include_files:
    - bin/activate
    - bin/deactivate

requirements:
  build:
    - python
  run:
    - python
    - conda
 
test:
  commands:
    - conda env -h
    - command -v activate
    - command -v deactivate
