package:
  name: clyent
  version: 1.0.0

source:
  git_url: https://github.com/Anaconda-Server/clyent.git
  git_tag: 1.0.0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - clyent
