package:
  name: binstar
  version: 0.9.6.dev

source:
  git_url: https://github.com/pelson/binstar.git
  git_tag: raspberry_pi_support

build:
  script:
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - clyent
    - requests
    - pyyaml
    - dateutil
    - pytz
