package:
  name: numpy
  version: 1.13.0

source:
  fn: numpy-1.13.0.tar.gz
  url: https://github.com/numpy/numpy/releases/download/v1.13.0/numpy-1.13.0.tar.gz
  md5: 39ae7fd9b6b09847cde5cd8ea0672757

build:
  number: 1

requirements:
  build:
    # NOTE: requires "apt-get install gfortran libatlas-dev"
    - python
  run:
    - python

test:
  imports:
    - numpy

about:
  home: http://numpy.scipy.org/
  license: BSD
