package:
  name: conda
  version: 3.12.0

source:
  git_url: https://github.com/conda/conda
  git_tag: 3.12.0

always_include_files:
    - bin/conda

requirements:
  build:
    - python
  run:
    - python
    - pycosat
    - pyyaml
    - requests

build:
  number: 3

test:
  imports:
    - conda
  commands:
    - conda info
