package:
  name: python
  version: "3.4.3"

source:
  fn: Python-3.4.3.tar.xz
  url: https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tar.xz
  patches:
    - buildinfo.patch
    - getpath.patch

build:
  number: 1

requirements:
  build:
    - zlib
    - readline
    - sqlite
    - bzip2
    - openssl
  run:
    - zlib
    - readline
    - sqlite
    - bzip2
    - openssl

test:
  commands:
    - python3 --version
    - python3-config --prefix
  imports:
    - sys
    - os
    - sqlite3
    - readline
    - bz2
    - ssl

about:
  home: https://www.python.org
  license: PSF
