package:
  name: jinja2
  version: "2.7.3"

source:
  fn: Jinja2-2.7.3.tar.gz
  url: https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.3.tar.gz
  md5: b9dffd2f3b43d673802fe857c8445b1a

requirements:
  build:
    - python
    - setuptools
    - markupsafe

  run:
    - python
    - setuptools
    - markupsafe

test:
  imports:
    - jinja2
    - jinja2.testsuite
    - jinja2.testsuite.res

about:
  home: http://jinja.pocoo.org/
  license:  BSD License
  summary: 'A small but fast and easy to use stand-alone template engine written in pure python.'

