package:
  name: anaconda-client
  version: 1.0.2

source:
  git_url: git@github.com:Anaconda-Server/anaconda-client.git
  git_tag: 1.0.2

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - clyent >=0.4
    - requests
    - pyyaml
    - python-dateutil
    - pytz
    - pillow

test:
  imports:
    - binstar_client
  commands:
    - anaconda upload --help
