package:
  name: matplotlib
  version: 1.4.2

source:
  git_url: https://github.com/matplotlib/matplotlib
  git_tag: v1.4.2
  

requirements:
  build:
    - numpy
    - dateutil
    - nose
    - pyparsing
    - pytz
    - tornado
    - distribute
    - libpng
    - mock
    - tk
  run:
    - mock
    - tk
    - python
    - numpy
    - dateutil
    - pytz
    - libpng
    - pyparsing

