package:
  name: pip
  version: "7.1.2"

source:
  url: https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz
  fn: pip-7.1.2.tar.gz
  md5: 3823d2343d9f3aaab21cf9c917710196

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  commands:
    - pip --help
  imports:
    - pip
