package:
  name: clyent
  version: 0.3.2

source:
  git_url: https://github.com/binstar/clyent.git
  git_tag: 0.3.2

build:
  script:
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
