package:
  name: clyent
  version: 0.4.0

source:
  git_url: https://github.com/binstar/clyent.git
  git_tag: 0.4.0

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
  run:
    - python
