package:
  name: libtiff
  version: 4.0.8

source:
  fn: tiff-4.0.8.tar.gz
  url: ftp://download.osgeo.org/pub/libtiff/tiff-4.0.8.tar.gz
  md5: 2a7d1c1318416ddf36d5f6fa4600069b

requirements:
  build:
    - zlib
    - jpeg 9*
  run:
    - jpeg 9*

about:
  home: http://www.simplesystems.org/libtiff/
