{% set version = "3.3.0" %}

package:
  name: opencv
  version: {{ version }}

source:
  fn: opencv-{{ version }}.tar.gz
  url: https://github.com/opencv/opencv/archive/{{ version }}.tar.gz
  sha256: 8bb312b9d9fd17336dc1f8b3ac82f021ca50e2034afc866098866176d985adc6

build:
  number: 0
  features:
    - neon_turbojpeg_tbb  # [not win]

requirements:
  build:
    # apt-get install cmake
    - python
    - toolchain
    - pkgconfig
    - eigen 3.2.*
    - zlib 1.2.*
    - libtiff 4.0.*
    - numpy >=1.9.*
    - libpng 1.6.*
    - libjpeg-turbo
    - jasper

  run:
    - python
    - zlib 1.2.*
    - libtiff 4.0.*
    - numpy >=1.9
    - libpng 1.6.*
    - libjpeg-turbo
    - jasper

test:
    imports:
      - cv2

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.
