package:
  name: picamera
  version: "1.13"

source:
  fn: picamera-1.13.tar.gz
  url: https://pypi.python.org/packages/79/c4/80afe871d82ab1d5c9d8f0c0258228a8a0ed96db07a78ef17e7fba12fda8/picamera-1.13.tar.gz
  md5: 47e815b0f21bba2a91ab3c4cd36c6f90

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - picamera

about:
  home: http://pypi.python.org/pypi/picamera/
  license: BSD License
  summary: 'A pure Python interface for the Raspberry Pi camera module'

