package:
  name: libnetcdf
  version: 4.2.1.1

source:
  fn: netcdf-4.2.1.1.tar.gz
  url: https://github.com/Unidata/netcdf-c/archive/netcdf-4.2.1.1.tar.gz
  md5: 42875052d3b8639e273afb3f988c4430

requirements:
  build:
    - curl
    - hdf5
    - zlib
  run:
    - curl
    - hdf5
    - zlib

test:
  commands:
    - ncdump
    - nc-config --help

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
