package:
  name: pycosat
  version: 0.6.0

source:
  url: https://pypi.python.org/packages/source/p/pycosat/pycosat-0.6.0.tar.gz#md5=b2bf00788b2607514b8cd5951217a888
  fn: pycosat-0.6.0.tar.gz

build:
  script:
    - $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
