package:
  name: pycosat
  version: 0.6.1

source:
  url: https://github.com/ContinuumIO/pycosat/archive/0.6.1.tar.gz
  fn: 0.6.1.tar.gz

build:
  script:
    - $PYTHON setup.py install
  number: 2

requirements:
  build:
    - python
    - setuptools
  run:
    - python
