package:
  name: pyparsing
  version: 2.0.1

source:
  fn: pyparsing-2.0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pyparsing/pyparsing-2.0.1.tar.gz
  md5: 37adec94104b98591507218bc82e7c31

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - pyparsing

about:
  home: http://pyparsing.wikispaces.com/
  license: MIT License

