package:
  name: cython
  version: 0.23.1

source:
  git_url: git@github.com:cython/cython.git
  git_tag: 0.23.1

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

build:
  number: 1
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main

test:
  imports:
    - cython
  commands:
    - cython --help
