package:
  name: jpeg
  version: 9b

source:
  fn: jpegsrc.v9b.tar.gz
  url: http://download.openpkg.org/components/cache/jpeg/jpegsrc.v9b.tar.gz

about:
  home: http://www.ijg.org/
  license: Custom free software license
  summary: read/write jpeg COM, EXIF, IPTC medata
