package:
  name: libpng
  version: 1.6.29

source:
  fn: libpng-1.6.29.tar.gz
  url: https://downloads.sourceforge.net/project/libpng/libpng16/1.6.29/libpng-1.6.29.tar.gz

requirements:
  build:
    - zlib

about:
  home: http://www.libpng.org/pub/png/libpng.html
  license: Open Source (http://www.libpng.org/pub/png/src/libpng-LICENSE.txt)
